import React from 'react';
import Head from 'next/head';
import { Metadata } from 'next';

import Title from '@/components/Title';
import styles from './styles.module.css';
import { LOCALES } from '@/types';
import { useLanguage } from '@/hooks/useLanguage';

export const metadata: Metadata = {
  title: 'Maco',
  description: 'Generated by create next app',
};

const About = () => {
  const { about } = useLanguage();
  const { title = '', description = [] } = about;

  return (
    <section className={styles.aboutContainer}>
      <Head>
        <title>{title}</title>
      </Head>
      <Title>{title}</Title>
      <div className={styles.textWrapper}>
        <div className={styles.textBlock}>
          {description.map((paragraph: string, index: number) => (
            <p key={index} className="about-wrapper__info-text">
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </section>
  );
};

export default About;
