import React from 'react';
import Head from 'next/head';
import { Metadata } from 'next';

import Title from '@/components/Title';
import { useLanguage } from '@/hooks/useLanguage';
import styles from './styles.module.css';

export const metadata: Metadata = {
  title: 'Maco',
  description: 'Generated by create next app',
};

const About = () => {
  useLanguage();
  return (
    <section className={styles.aboutContainer}>
      <Head>
        <title>Me</title>
      </Head>
      <Title>Me</Title>
      <div className={styles.textWrapper}>
        <div className="about-wrapper__info">
          <p className="about-wrapper__info-text">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
            neque, ipsa animi maiores repellendu distinctioaperiam earum dolor
            voluptatum consequatur blanditiis inventore debitis fuga numquam
            voluptate architecto itaque molestiae.
          </p>
          <p className="about-wrapper__info-text">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
            neque, ipsa animi maiores repellendu distinctioaperiam earum dolor
            voluptatum consequatur blanditiis inventore debitis fuga numquam
            voluptate architecto itaque molestiae.
          </p>
          <p className="about-wrapper__info-text">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
            neque, ipsa animi maiores repellendu distinctioaperiam earum dolor
            voluptatum consequatur blanditiis inventore debitis fuga numquam
            voluptate architecto itaque molestiae.
          </p>
          <p className="about-wrapper__info-text">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit. Excepturi
            neque, ipsa animi maiores repellendu distinctioaperiam earum dolor
            voluptatum consequatur blanditiis inventore debitis fuga numquam
            voluptate architecto itaque molestiae.
          </p>
          <p className="about-wrapper__info-text">
            Lorem ipsum dolor sit, amet consectetur adipisicing elit.
          </p>
        </div>
      </div>
    </section>
  );
};

export default About;
