import React from 'react';
import Head from 'next/head';
import { Metadata } from 'next';

import Title from '@/components/Title';
import { useLanguage } from '@/hooks/useLanguage';

export const metadata: Metadata = {
  title: 'Maco',
  description: 'Generated by create next app',
};

const About = () => {
  const { about } = useLanguage();
  const { title = '', description = [] } = about;

  return (
    <section className="about-container">
      <Head>
        <title>{`Marco Franceschi 🙋🏽‍♂️ ${title}`}</title>
      </Head>
      <Title>{title}</Title>
      <div className="text-wrapper">
        <div className="text-block">
          {description.map((paragraph: string, index: number) => (
            <p key={index} className="about-text-paragraph">
              {paragraph}
            </p>
          ))}
        </div>
      </div>
    </section>
  );
};

export default About;
