import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import Line from '@/components/Line';
import Footer from '@/components/Footer';
import Header from '@/components/Header';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Maco',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <>
      <Header />
      <main className="main">{children}</main>
      <Footer />
      <Line position="top" />
      <Line position="bottom" />
      <Line position="left" />
      <Line position="right" />
    </>
  );
}
